[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
indent-size = 4

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true